<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-27 17:15
=======
# Generated by Django 4.2.3 on 2023-07-27 05:21
>>>>>>> main

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
>>>>>>> main
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
