version: "3"
services:

  mysql:
    image: mysql:5.7
    env_file:
      - ./.env
    container_name: ainterview_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # 가상 네트워크 연결
    networks:
      - ai_net

  backend:
    env_file:
      - ./.env
    image: backend
    build:
      # context : 현재 폴더에 있는 도커파일을 쓰겠다.
      context: .
      dockerfile: dockerfile
    container_name: backend_service
    volumes:
      - .:/app
    # command : 컨테이너가 띄워질 때 실행하는 명령어 / 서버실행
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    ports:
      - 8000:8000
    # 가상 네트워크 연결
    links:
      - mysql:mysql
    networks:
      - ai_net

networks:
  ai_net:
    driver: bridge