version: "3"
services:

  backend:
    env_file:
      - ./.env
    image: backend
    build:
      # context : 현재 폴더에 있는 도커파일을 쓰겠다.
      context: .
      dockerfile: dockerfile
    container_name: backend_service
    volumes:
      - .:/app
    # command : 컨테이너가 띄워질 때 실행하는 명령어 / 서버실행
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    ports:
      - 8000:8000
    # 가상 네트워크 연결
    networks:
      - ai_net

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq_service
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672
    expose:
      - 5672
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - backend
    networks:
      - ai_net

  celery:
    container_name: celery_service
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    # command: sh -c "celery -A ainterview worker -l info --pool=solo"
    command: sh -c "celery -A ainterview worker -l info"
    
    networks:
      - ai_net
    depends_on:
      - rabbitmq
      - backend

networks:
  ai_net:
    driver: bridge