version: "3"
services:

  mysql:
    image: mysql
    env_file:
      - ./.env
    command: --lower_case_table_names=1
    container_name: ainterview_db # 컨테이너 이름 설정
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER} # db가 생성될 때 유저도 같이 생성
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # 가상 네트워크 연결
    networks:
      - ai_net

  backend:
    env_file:
      - ./.env
    build:
      # context : 현재 폴더에 있는 도커파일을 쓰겠다.
      context: .
      dockerfile: dockerfile
    container_name: backend
    volumes:
      - .:/app
    # command : 컨테이너가 띄워질 때 실행하는 명령어 / 서버실행
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    ports:
      - 8000:8000
    # 가상 네트워크 연결
    networks:
      - ai_net
    depends_on:
      - mysql

networks:
  ai_net:
    driver: bridge
